### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by waynebrantley** [CaptiveAire/Seq.App.YouTrack#7] opened 2017-08-29 21:42 UTC
I setup a manually triggered instance
I sent an error to it.   A notify box comes up and says it was sent.
It does not show up in YouTrack.
There are no 'events raised by this add-in' in seq.
I have looked in seq logs and youtrack logs and see nothing about a failed call or anything (assuming I am looking in the right log files...but I looked in all the ones I could find).

How do we troubleshoot this add-in?
Seq 4.1.17

**Comment by nblumhardt** [comment] 2017-08-29 21:54
I think the problem is:

https://github.com/CaptiveAire/Seq.App.YouTrack/blob/master/src/YouTrackIssuePoster.cs#L313

This is logging to the Serilog default log, which won't be configured to send events back to Seq. I think the logging should be going to `Host.Logger` instead.

It's also fine (and maybe preferable) for apps to just throw exceptions out of `On` for Seq to handle and log, although the event won't be as detailed as the one the app is creating.

**Comment by Jaben** [comment] 2017-08-30 01:34
@nblumhardt Appreciate the attention on this one -- I wasn't sure what's considered best practice. Host.Logger does appear to exist? Fine by me to to just let be uncaught...

**Comment by Jaben** [comment] 2017-08-30 02:07
@nblumhardt Nevermind Nick -- figured it out. :)

**Comment by Jaben** [comment] 2017-08-30 02:43
@waynebrantley Update to the latest version of the plugin and try again -- it should properly log the issue now.

**Comment by nblumhardt** [comment] 2017-08-30 04:05
Change looks like the right one; sorry about the `Host` confusion, Jaben - I was looking at the other side of the API :-)

**Comment by Jaben** [comment] 2017-08-30 04:25
Honestly, it's a bit confusing. In class it's Log (host instance) and static it's Log (global) -- very different things. Got me!

**Comment by nblumhardt** [comment] 2017-08-30 06:36
Agreed - I would go back and change this API, if I could without breaking things. I think there may be a chance to make some improvements now that the host process is not Seq - either by encouraging the new apps-as-EXEs pattern, or having a new version of the host process deployed to support breaking changes in the package API. Will see how things look a little further down the track... 👍

**Comment by Jaben** [comment] 2017-08-30 12:01
@nblumhardt Fantastic! 

@waynebrantley closing this issue for now.

**Closed by Jaben** 2017-08-30 12:01 UTC

**Comment by waynebrantley** [comment] 2017-08-30 12:22
I have error messages now.  Thanks!
